### ISSUE TITLE
[Question] Dual mode generic

### ISSUE THREAD

**Issue by limkinZero** [swingerman/ha-dual-smart-thermostat#111]
I would like to know if there would be the possibility of having a new dual mode to control a heater and a cooler that, depending on the mode it is in (heater), does one thing or reverses the logic if it is in cold mode.

As of today, I am using another HACS integration called [Dual Mode Generic Thermostat](https://github.com/zacs/ha-dualmodegeneric) but it has not been maintained for a couple of years and is using deprecated properties.

The idea is to control an electro valve so that it opens or closes depending on a temperature sensor. If in heat or winter mode, open when the room temperature is below the set temperature. And if the system is in summer/cooler mode, open or close that same switch but inverting the logic.

Regards.

**Comment by swingerman** [comment]
You can use this component. You will need to create an inverted switch for the cooling mode. If both heater and cooler are set, you will be able to set low and high temperatures (range mode)

**Comment by swingerman** [comment]
You can create a [template switch](https://www.home-assistant.io/integrations/switch.template/) from your existing switch and use it for cooling mode.
I still don't seem to understand fully how your existing switch should work in heating and cooling mode though.

**Comment by limkinZero** [comment]
Yes, I know. I can use a template but I would like to know why the plugin restricts that the switch cannot be the same for the heater and the cooler. 

In Spain and many other European countries. Especially in the south, aerothermal air/water conditioning systems with radiant floor emitters are being installed. The idea is climate the house using cold water or hot water. With this system, the only switch there is is the one that controls the electro valve that allows the water to pass through. That's why I think the plugin should remove that restriction.

**Comment by serlinGi** [comment]
> You can create a [template switch](https://www.home-assistant.io/integrations/switch.template/) from your existing switch and use it for cooling mode. I still don't seem to understand fully how your existing switch should work in heating and cooling mode though.

I opted for an input_boolean.virtual_switch that activates under certain conditions;  I think what you say is correct @limkinZero : those of us who use air/water fan coils find ourselves managing everything with a single switch

**Comment by paulius2k** [comment]
Same thing was discussed in #43
