### ISSUE TITLE
Climate entity has no unique_id: Can't set Area

### ISSUE THREAD

**Issue by jkrasinger** [swingerman/ha-dual-smart-thermostat#128]
When creating an "dual_smart_thermostat" entity in HA, this entity has no unique_id. 

It is also not possible to define a unique_id in configuration. 

For this an "area" can not be assigned to this climate entity.

![Screenshot_dual_thermostat](https://github.com/swingerman/ha-dual-smart-thermostat/assets/8291803/365f45ab-e4d0-4b77-b5c6-18e93c690041)

**Comment by swingerman** [comment]
You can define a unique_id for this component

**Comment by jkrasinger** [comment]
👍👍👍
