### ISSUE TITLE
Feature request: additional attribute or hvac_state if thermostat is "idle" due to an "opening"

### ISSUE THREAD

**Issue by jkrasinger** [swingerman/ha-dual-smart-thermostat#129]
hvac_state shows "idle" if thermostat is outside the defined temperature tolerance.

When a sensor in "opening" is active, the hvac_state is also in "idle". 

It would be great if a distinction were made between an "opening" and an "out of temperature" status. For example, an additional attribute "opening" (true, false) or an additional "hvac_state" (e.g. "opening" instead of "idle").

This could then be displayed in a Lovelace card and is therefore more meaningful.

**Comment by swingerman** [comment]
That would be nice indeed. Not to mention the floor temp based idle state.
The thermostat cards only support the states of the built-in climate entity. To achieve what you request we could only use a custom thermostat card that supports these extra values.
In short. I don't see a chance to make anything not supported by Lovelace cards appear on them from this component.

**Comment by jkrasinger** [comment]
You are right, the "normal" Thermostat cards can not display this information. But I use the mushroom template card for this purpose, and with this I can display this information.

![Screenshot_dual_thermostat_template](https://github.com/swingerman/ha-dual-smart-thermostat/assets/8291803/5ccdbfcb-541b-46c8-8c37-2c698e9adf2b)

**Comment by jkrasinger** [comment]
BTW: The normal thermostat cards also show the "hvac_state":

![Screenshot_dual_thermostat_template2](https://github.com/swingerman/ha-dual-smart-thermostat/assets/8291803/b4901c3b-f651-4ff2-af79-4f6007f8c85d)

"Untätitg" = Idle"

**Comment by swingerman** [comment]
As far as I know, hvac_state has limited options. (those that are defined in the core climate integration). I can be wrong though.

**Comment by swingerman** [comment]
Unfortunately, the built-in HVACAction is limited to the predefined values: (#hvac-action)[https://developers.home-assistant.io/docs/core/entity/climate/#hvac-action].

Our only option is to introduce a custom property, like "idleReason", that can be used with custom thermostat cards. Or maybe with some UI plugin.

**Comment by jkrasinger** [comment]
Yes, I'm afraid I didn't express myself precisely enough, but the introduction of an additional property (i called it "attribute" above)  (e.g. idleReason) would be a really good extension. The standard thermostat card would ignore it, but custom elements can use it. Perfect

**Comment by swingerman** [comment]
It seems that I can implement it by providing a sensor entity for the thermostat that holds the reason for the current HVAC action. 

I will ook into this...

**Comment by jkrasinger** [comment]
I think that's a great alternative idea. As I am not a developer for HA I have not read the technical specifications, but an additional sensor cannot be a problem at all.

Sounds extremely good!

**Comment by jkrasinger** [comment]
However, I'd be happy with any solution :satisfied:

**Comment by swingerman** [comment]
Please check [v0.9.5-beta.4](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.5-beta.4)

A new state attribute, `hvac_action_reason`, was added. See more in the readme.

**Comment by jkrasinger** [comment]
@swingerman : I have tested the version v0.9.5-beta.4 in terms of my request. The new attribute "hvac_action_reason" perfectly shows the current "reasons" for the idle status as well as the heating status. This really helps now for the own dashboard elements.

Thanks for this quick extension. :thumbsup:
