### ISSUE TITLE
[feature] Allow heater and cooler be the same entity  in heat_cool_mode

### ISSUE THREAD

**Issue by NoobyNiceDev** [swingerman/ha-dual-smart-thermostat#142]
Hey!
I have a very specific request. I'm using a heatpump with floor heating which automatically switches between heating and cooling mode depending on outside temperature. The cooling mode is limited to round about 5K below outside temp and is secured by some dew point sensor.

So if it's cold, the room-thermostat has to be opened to let warm water inside the floor heating.
If it's warm, the same valve has to be opened to let cold water inside the floor "heating" and cool the room.

Reason for using this module: It shall open the very same valve/switch if it's colder as selected temperatur (+ some tolerance) or if it's hotter (+ some tolerance). Maybe with manual switch of the mode. Obviously I have to make sure, that my heatpump has switched it's mode from heating to cooling. 

```
- platform: dual_smart_thermostat
  name: Wohnzimmer
  heater: switch.shelly1minig3_redacted-id_switch_0
  cooler: switch.shelly1minig3_redacted-id_switch_0
  target_sensor: sensor.wohnzimmer_hut_temperature
  heat_cool_mode: true # <-required
  initial_hvac_mode: "heat_cool"
  unique_id: wz_heatcool
```

With this configuration, the entity allows only heating.

![grafik](https://github.com/swingerman/ha-dual-smart-thermostat/assets/33202028/486df447-ef53-49af-a4eb-6ea89aca4432)

**Comment by swingerman** [comment]
This question has been asked many times. It's a tricky edge case as the thermostat component currently cannot determine if it's summer or winter.
My suggestion is to:

1. create an input boolean for winter mode that you will manually switch, or if you have a sensor for that, use that
2. create a template switch for heating using the above input_boolean/sensor + switch.shelly1minig3_redacted-id_switch_0
3. create a template switch for cooling using the above input_boolean/sensor + switch.shelly1minig3_redacted-id_switch_0

The switch you create in step 1 should reverse the logic of the switches you create in steps 2-3.
