### ISSUE TITLE
Entity None warning

### ISSUE THREAD

**Issue by baunan** [swingerman/ha-dual-smart-thermostat#149]
Getting this warning in the log when starting HA

"Entity None (<class 'custom_components.dual_smart_thermostat.climate.DualSmartThermostat'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/swingerman/ha-dual-smart-thermostat/issues"

version 0.9.4 of dual smart and 2024.2.5 on HA.

**Comment by swingerman** [comment]
Please try the lastest version.

**Comment by baunan** [comment]
Message is gone now with the new version. Thank you
