### ISSUE TITLE
0.9.5 Update removed cool mode on my thermostat

### ISSUE THREAD

**Issue by NightHawkATL** [swingerman/ha-dual-smart-thermostat#150]
I just updated to 0.9.5 and saw that the one thermostat I am running as a dual thermostat was missing the cool mode. I didn't change any of the config in yaml but it was missing. I re-downloaded 0.9.4 and it came back.

Yaml code for thermostat:
```
- platform: dual_smart_thermostat
  name: Master Bed Thermostat
  target_sensor: sensor.master_bed_temp_sensor_temperature
  heater: switch.master_bed_fireplace_switch
  cooler: switch.portable_ac_on_off
#  target_temp: 66
  min_temp: 58
  max_temp: 80
  initial_hvac_mode: "off"
  precision: 1.0
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  #  openings:
#    - sensor.window1
#    - sensor.window2
```

**Comment by aliaghil** [comment]
I am also facing something similar.
In my case, I lost both cooling and heating functionality. For example, every time I turn on cool mode, it will turn on the Cool/Heat, and it does not turn on the `input_boolean.aircon_cool_switch` for me., although the current temperature is 2-3 degrees higher than the `target_temp_high`

Here are my Dual Thermostat settings:
`
# Dual thermostat
  - platform: dual_smart_thermostat
    name: Air Conditioner
    unique_id: Air_Conditioner
    heater: input_boolean.aircon_heat_switch
    cooler: input_boolean.aircon_cool_switch
    target_sensor: sensor.average_house_temp
    min_temp: 16
    max_temp: 32
    ac_mode: false
    target_temp: 26.5
    target_temp_high: 26.5
    target_temp_low: 23.0
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
`

**Comment by SEKCobra** [comment]
I am also affected by this, I assume it is because I have explicitly removed heat_cool mode and I think this update reinterprets this to mean no cooling at all, rather than having explicit cool and explicit heat.

**Comment by NightHawkATL** [comment]
> I confirm that with heat_cool_mode True
> 
> ![Screenshot_2024-04-15-10-55-04-47_c3a231c25ed346e59462e84656a70e50](https://github.com/swingerman/ha-dual-smart-thermostat/assets/63103970/4495660d-e8eb-41a1-8c44-035ef469107c)
> 
>  it seems to work correctly

The issue is that it will show both setpoints no matter what in that mode. If I am in heat mode, I expect it to only show the heat setpoint. If I am in cool mode, I only expect to see the cool setpoint. I know what to do but it would confuse my wife so I am sticking to 0.9.4 until I know a new fix.

**Comment by swingerman** [comment]
I will create a release from v9.5.5.beta-4. It's without refactoring.
A new beta will come with refactored stuff under v9.6.0.beta-1
