### ISSUE TITLE
[feat] restore last used HVAC mode on toggle

### ISSUE THREAD

**Issue by jacobw** [swingerman/ha-dual-smart-thermostat#159]
Toggle always sets heat_cool mode, instead of setting turning on the previous mode. It would be great if it remembered the last mode and toggled that as I constantly use the same mode all season usually (i.e cool mode in summer).

My family use case is generally just turn it on while family is sleeping per room, and turn it off when they are off, so toggle would work ideally for this. The standard climate control works this way, so its seems like a good standard.

I've tried to work around this issue but haven't found a way without manually choosing cool each time, which either required more buttons on the dashboard, or opening up the more info controller, which is a much fiddlier. For now I've just disabled the heater.

Thanks for the great project!

**Comment by swingerman** [comment]
Do you toggle it with an automation?

**Comment by jacobw** [comment]
> Do you toggle it with an automation?

No, tap action in tile card.

**Comment by jacobw** [comment]
Ok great. I'll test when you release. Also I think your installation instructions still referred to the old HACS integration section.

**Comment by swingerman** [comment]
The beta is out

**Comment by jacobw** [comment]
Related question, I tried to turn off heater mode do toggle would make it fog to cool mode, and I could not flush the old temp high and low state from HA. I ended up having to increment the unique_id to pick up the new settings. Tried restarting and manually deleting the entity and nothing would work. Was about to start trying to investigate internal databases to see where the state was saved but do you know how to fix this?

**Comment by jacobw** [comment]
Working well thanks!
