### ISSUE TITLE
[feat] enable other climate options

### ISSUE THREAD

**Issue by jacobw** [swingerman/ha-dual-smart-thermostat#160]
I'm not sure if this is too complicated, but the climate card only allows. me to set a subset of my heat pump options, so I find I have to have a second card to get to the real climate control to set the other options. is it possible to support this directly in your climate   entity. The main missing element is fan mode. Ideally I'd be able to set this directly ,and then have it remember the mode the next time it turned on or I toggled it. The other mode I am missing is swing mode, but I change that far less.

**Comment by swingerman** [comment]
Sorry, could you describe the features you are missing?
Fan mode is in the works. An alpha release is coming out today!
#47

**Comment by swingerman** [comment]
Fan feature is out: https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-2

**Comment by jacobw** [comment]
Hi, thanks for the amazing fast responses!

I mean these modes:
fan_modes: auto, minimum, low, medium-low, medium, medium-high, high, very-high, max
swing_modes: auto-vert, upper, upper-central, central, lower-central, lower

<img width="990" alt="Screenshot 2024-04-19 at 5 57 44 AM" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/152987/227a83c3-1208-45b3-af9e-6c8333b0a187">

**Comment by swingerman** [comment]
Not sure about this.
How would this component control fan speed and swing?
