### ISSUE TITLE
[feat] Safety disable if sensor unavailable

### ISSUE THREAD

**Issue by jacobw** [swingerman/ha-dual-smart-thermostat#168]
[versatile_thermostat](https://github.com/jmcollin78/versatile_thermostat) has a nice [feature](https://github.com/jmcollin78/versatile_thermostat?tab=readme-ov-file#advanced-configuration) (security_delay_min) to disable the thermostat if a temperature hasn't been updated for a configurable about of time.

This would be helpful to me as my temperature sensors are battery based and could fail.

Any interest in creating a feature like that?

**Comment by swingerman** [comment]
Seems like a good feature. I will schedule it for implementation.
Should the thermostat be completely off or just idle?

**Comment by jacobw** [comment]
Thank you!

Good question, off the top of my head, ideally configurable, but for me idle so it will start climate control if the sensor recovers. Maybe that's asking for trouble though.

**Comment by swingerman** [comment]
Idle is easier and seems to be more logical.
The thermostat will still be in the same HVAC mode but in an idle state, and as soon as the sensor recovers, it will continue to control the climate.

**Comment by jacobw** [comment]
Yes sounds sensible. Will you include a configurable timeout? Allow people to tune based on how fast or slow overheating or cooling can happen.

**Comment by swingerman** [comment]
Sure

**Comment by swingerman** [comment]
Implementation is done. Will be included in next release and betas.

**Comment by jacobw** [comment]
Thank you for you great work!

**Comment by jacobw** [comment]
Just checking - is the setting in seconds? I'm not sure what time delta is if the README. Perhaps add it to the example config?

I found this:
        """Checks when the sensor was last updated. If the sensor has not been
        updated in the last sensor_safety_delay seconds, the sensor is considered
        timed out."""

**Comment by swingerman** [comment]
My bad. It's any valid timedelta

**Comment by jacobw** [comment]
So something like minutes=10 ?

**Comment by swingerman** [comment]
Yup

**Comment by jacobw** [comment]
Maybe I misunderstand. Just got Ann error with that:

```Configuration warnings
Invalid config for 'dual_smart_thermostat' from integration 'climate' at configuration.yaml, line 54: offset minutes=5 should be format 'HH:MM', 'HH:MM:SS' or 'HH:MM:SS.F' for dictionary value 'target_sensor_safety_delay', got 'minutes=5'
```

**Comment by swingerman** [comment]
Sorry,

Please use it like this:

```yaml
target_sensor_safety_delay: 
   - minutes: 10
```

**Comment by jacobw** [comment]
Still not working.

Config
```
    target_sensor_safety_delay:
      - minutes: 5
 ```

Returns

```
Invalid config for 'dual_smart_thermostat' from integration 'climate' at configuration.yaml, line 22: offset [{'minutes': 5}] should be format 'HH:MM', 'HH:MM:SS' or 'HH:MM:SS.F' for dictionary value 'target_sensor_safety_delay', got [{'minutes': 5}]
```

**Comment by swingerman** [comment]
For now, you can use the suggested formats in the terror message "HH::MM:SS" or "HH:MM"

I will review this and update the docs accordingly.

**Comment by swingerman** [comment]
Update:
I will rename the settings in the following release to: `sensor_stale_duration`.

**Comment by jacobw** [comment]
If the sensor starts working again, will it auto reenable? If not, is that possible?

**Comment by swingerman** [comment]
Yes, the thermostat turns of switches but it doesn't go to `off` mode
