### ISSUE TITLE
Reload Config Temeprature

### ISSUE THREAD

**Issue by milandzuris** [swingerman/ha-dual-smart-thermostat#170]
Hi, when i reload config from developers tools temperature is set to other what is the set in cfg, always to 20.5

![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/8a907c4d-bc78-48ac-9454-5a053732f77a)
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/e59a840f-4db2-42df-9947-75c9a30fbf10)

**Comment by swingerman** [comment]
What version do you use?

**Comment by swingerman** [comment]
I tried it with the latest beta [v0.9.6.beta-5](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-5) and it seem to be fixed.
Could you confirm?

**Comment by milandzuris** [comment]
> I tried it with the latest beta [v0.9.6.beta-5](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-5) and it seem to be fixed. Could you confirm?

yes it works
