### ISSUE TITLE
Ccurrently the heat/cool fuction is not working with the fan-mode

### ISSUE THREAD

**Issue by swingerman** [swingerman/ha-dual-smart-thermostat#175]
Hi there, currently the heat/cool fuction is not working with the fan-mode includes  > Kan service climate/set_temperature niet aanroepen. unsupported operand type(s) for +: 'NoneType' and 'float'< 

climate:
  - platform: dual_smart_thermostat
    name: Climate
    heater: switch.verwarming_switch
    cooler: input_boolean.switch_airco_mode
    target_sensor: sensor.temp_1
    floor_sensor: sensor.temp_1
    max_floor_temp: 26
    min_floor_temp: 10
    fan: input_boolean.switch_fan_mode
    fan_hot_tolerance: 1
    target_temp_step: 0.5
    min_temp: 9
    max_temp: 32
    target_temp: 19.5
    target_temp_high: 20.5
    target_temp_low: 19.5

normal cool mode is working fine for me ( thx for that  😃)

_Originally posted by @rrterrorr in https://github.com/swingerman/ha-dual-smart-thermostat/issues/161#issuecomment-2087476985_

**Comment by swingerman** [comment]
Are you using the latest beta?

**Comment by rrterrorr** [comment]
Correct, the latest beta is in use

Op wo 1 mei 2024 09:42 schreef Miklos Szanyi ***@***.***>:

**Comment by swingerman** [comment]
Please check [v0.9.6.beta-6](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-6)

**Comment by grantland** [comment]
Updating to https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-9 fixed this issue for me
