### ISSUE TITLE
EventType and StrEnum  was deprecated ....in HA Core 20255. 

### ISSUE THREAD

**Issue by serlinGi** [swingerman/ha-dual-smart-thermostat#177]
Hi,
I just installed the new May version and this warnings appears:

- StrEnum was used from dual_smart_thermostat, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, ......
- EventType was used from dual_smart_thermostat, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.Event instead.....

... please report it to the author of the 'dual_smart_thermostat' custom integration.

Thx for all

**Comment by swingerman** [comment]
Fixed it. Will include it in the next release or beta
