### ISSUE TITLE
"latest beta" unable to set hvac mode after selecting preset

### ISSUE THREAD

**Issue by rrterrorr** [swingerman/ha-dual-smart-thermostat#178]
>off and heat/cool = working fine<

Kan service climate/set_hvac_mode niet aanroepen. 'FeatureManager' object has no attribute '_saved_target_temp_low'

climate:
  - platform: dual_smart_thermostat
    name: Climate Remo
    heater: switch.verwarming
    cooler: switch.airco
    heat_cool_mode: true
    target_sensor: sensor.temp
    floor_sensor: sensor.temp
    max_floor_temp: 26
    min_floor_temp: 10
    fan: switch.fan
    fan_hot_tolerance: 0.5
    target_temp_step: 0.5
    precision: 0.1
    min_temp: 9
    max_temp: 32
    target_temp: 20
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    initial_hvac_mode: "off" # hvac mode will reset to this value after restart
    away:
      temperature: 12
      target_temp_low: 12
      target_temp_high: 22.5
    home:
      temperature: 20
      target_temp_low: 19
      target_temp_high: 20.5
    sleep:
      temperature: 17
      target_temp_low: 17
      target_temp_high: 21
    eco:
      temperature: 19
      target_temp_low: 19
      target_temp_high: 21.5

**Comment by rrterrorr** [comment]
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/103316641/f03f86c7-a3f9-4277-89eb-120afb63409c)
As you can see in the image, there is something else going on. If the temperature is close to the desired setting, the mode goes from fan to air conditioning mode. I also removed the presets and then the HVAC Select works again

**Comment by rrterrorr** [comment]
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/103316641/fb1b9a9b-79f4-411f-8cbb-d7c9b7397d98)
As you can see in the image, there is something else going on. If the temperature is close to the desired setting, the mode goes from fan to air conditioning mode. I also removed the presets and then the HVAC Select works again

**Comment by swingerman** [comment]
> ![image](https://private-user-images.githubusercontent.com/103316641/327458772-fb1b9a9b-79f4-411f-8cbb-d7c9b7397d98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjE0MjgsIm5iZiI6MTcxNDcyMTEyOCwicGF0aCI6Ii8xMDMzMTY2NDEvMzI3NDU4NzcyLWZiMWI5YTliLTc5ZjQtNDExZi04Y2JiLWQ3YzliNzM5N2Q5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNzI1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjY0OTM1NmU3ZjQ2ZTJlZGUzNDRhYjc0MjNhNmVmYWI3ZWE0YTEwYTBhYjVhMzI2ZTJhZWJhMjM4ZTJkODJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.70pGFifGUpxshcEuxi5wBgyaP2dsNLeVP6Porbi6xWM) As you can see in the image, there is something else going on. If the temperature is close to the desired setting, the mode goes from fan to air conditioning mode. I also removed the presets and then the HVAC Select works again

I think its the fan_hot_tolerance working.

**Comment by rrterrorr** [comment]
hello, yes, if the temperature is a little further, it will first turn on
in fan mode and then up to the desired limit and then air conditioning.
only .1 / .2 degrees of desired temperature, which also turns on the air
conditioning instead of a fan

so imagine I need 20°C then it goes from 20.0 to 20.2 (plus minus) there it
turns on the air conditioning (I manually switch it on to see what happens
when it gets warmer) then to the limit fan mode and then the air
conditioning comes on. (I look at the HVAC actions there and not what is
being controlled)

is there something wrong in the config?

Op vr 3 mei 2024 10:51 schreef Miklos Szanyi ***@***.***>:
