### ISSUE TITLE
[Request] Set temperature value based on target_temp_* values when switching HVAC_Mode while Preset is set

### ISSUE THREAD

**Issue by T3chArmy** [swingerman/ha-dual-smart-thermostat#185]
When setting a preset while hvac_mode is not "heat_cool" while in "[DUAL Heat-Cool](https://github.com/swingerman/ha-dual-smart-thermostat?tab=readme-ov-file#dual-heat-cool-mode-example)" mode, if the temperature value is not defined, I think it would be good to select the temperature based on the mode,

if hvac_mode is cool, then set temperature to target_temp_low, if in heat set temperature to target_temp_high.

This will reduce/remove the need to update the config based on time of year.

**Comment by swingerman** [comment]
Implemented. Will be included in the next release/beta

**Comment by swingerman** [comment]
Please check [v0.9.7.beta-3](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.7.beta-3)

**Comment by T3chArmy** [comment]
I'm unable to test the feature for a couple weeks as I'm away. However, I glanced over the code and feature notes. Looks exactly like what I had in mind! 

Many thanks!
