### ISSUE TITLE
Invalid HVAC mode: None

### ISSUE THREAD

**Issue by T3chArmy** [swingerman/ha-dual-smart-thermostat#187]
When HA starts up this error is constantly thrown until hvac_mode is manually set.
```
This error originated from a custom integration.

Logger: custom_components.dual_smart_thermostat.hvac_device.cooler_fan_device
Source: custom_components/dual_smart_thermostat/hvac_device/cooler_fan_device.py:163
integration: dual_smart_thermostat (documentation, issues)
First occurred: 11:59:53 (173 occurrences)
Last logged: 13:23:42

Invalid HVAC mode: None
```

**Comment by T3chArmy** [comment]
I believe this issue is this line:

https://github.com/swingerman/ha-dual-smart-thermostat/blob/9defd2bcb45f4485652c6823a8128e910aa04023/custom_components/dual_smart_thermostat/hvac_device/cooler_fan_device.py#L64

Should the old state be getting restored here if it's not defined in the config?

**Comment by T3chArmy** [comment]
Disregard that last comment, even with a value set for initial_hvac_mode this error gets thrown.

**Comment by swingerman** [comment]
Will be included in the next release

**Comment by T3chArmy** [comment]
I'm not sure this is fixed, the thermostat fails to function until I manually set an hvac_mode after startup.

**Comment by T3chArmy** [comment]
@swingerman There unfortunately still seems to be an issue. Thermostat does not seem to be working still at HA startup until hvac_mode is manually changed.

**Comment by T3chArmy** [comment]
@swingerman I have tried it both defined and undefined. Neither one seems to work. It appears to restore the state correctly when undefined as expected with latest beta. However, it appears to never activate the switches until after the hvac_mode is changed. I wonder if this could possibly be due to the thermostat initializing before the Zigbee switches become available? I'm not sure.

I have also noticed the hvac_action_reason doesn't get set either until I change the hvac_mode. Figured if it was a switch issue it would show malfunction or misconfiguration.

**Comment by T3chArmy** [comment]
I turned on debug logging. Hope this provides some better insight to my issue. 

[error_log-2.txt](https://github.com/swingerman/ha-dual-smart-thermostat/files/15266474/error_log-2.txt)

**Comment by swingerman** [comment]
I managed to reproduce this and also managed to ensure the climate devices gets controlled on startup

**Comment by swingerman** [comment]
Please check with [v0.9.6.beta-10](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.6.beta-10)

**Comment by T3chArmy** [comment]
@swingerman 🎉 Excellent! Looks like it's working now! Thanks for getting this resolved! I think this fixes all the issues I have been experiencing! :)
