### ISSUE TITLE
Feature Request: Enable/disable fan_hot_tolerance based on outside air temperature

### ISSUE THREAD

**Issue by Jeepmb** [swingerman/ha-dual-smart-thermostat#195]
I recently implemented the new "fan" features in v0.9.6 into my config, and they work great! Specifically, I really enjoy the fan_hot_tolerance feature to employ the fan to cool the house before using the air conditioner.

However, in my house the intake for the fan is always outside (fresh) air. This means that if it is hotter outside than the set point, I'm actually _warming_ the house during the fan_hot_tolerance phase before cooling it with the air conditioner. But I also live in a climate where it can be cooler outside than inside even in the middle of summer, where there could be substantial benefit and cost savings by using fan_hot_tolerance to prioritize ouside air with the fan instead of spinning up the air conditioner.

My thought was to add a configuration option for an outside temperature sensor. Then, a logic that would look roughly like this:
- Outside Air Temp > High Set Point  = fan_hot_tolerance disabled (A/C runs exclusively)
- Outside Air Temp < High Set Point  = fan_hot_tolerance enabled (Fan runs before AC)

This is the simplest way I can think of handling this. Taking it a step further, an additional config option could possibly be implemented to ONLY use the fan for cooling if the outside temperature is below the high set point, eliminating A/C use entirely unless it's hotter outside than the set point.

I'll be looking into implementing this myself outside of the thermoatat integration via automation logic, but it could be a neat way to manage cooling in an energy efficient way. I realize it takes a good deal of time to build and maintain this project, so I appreciate the efforts!

**Comment by swingerman** [comment]
This will require the outside temperature sensor and a flag that enables it, as not all fans use outside air.

**Comment by Jeepmb** [comment]
Agreed. I was thinking about the flag, perhaps it could be labeled something like:

fresh_air_fan: true

While this label doesn't reference the "auto fan" function explicitly, i figure the combination of this plus the fan_hot_tolerance flag could enable the feature, and leave a nice config flag for other "fresh air" related functions in the future.

**Comment by swingerman** [comment]
Implementation is completed; will include it in the next release/beta.
