### ISSUE TITLE
Support dry mode

### ISSUE THREAD

**Issue by jamesduke** [swingerman/ha-dual-smart-thermostat#199]
Many wall mount HVAC systems support drying only mode to reduce humidity in the room. ha-dual-smart-thermostat makes a great overlay on top of those systems to implement twin set points where the underlying climate component does not support it. It's reasonably straightforward to implement a binary switch to enable/disable dry mode on these units if ha-dual-smart-thermostat  was to support a DRY only mode.

**Comment by swingerman** [comment]
Duplicate of #25

**Comment by swingerman** [comment]
It's more complex.

Of course, I could just add a switch for the dehumidifier to turn on/off, but it needs some other stuff required by the underlying climate entity built into the home assistant.
And if I just added the toggle, others will rightfully request a fully featured hygrostat.

So I will implement a fully featured hygrostat.
This will involve:
- dryer switch
- humidity sensor
- min/max humidity
- humidity tolerances

Stay tuned!

**Comment by jamesduke** [comment]
Well that would be amazing, and apologies for the dupe

**Comment by swingerman** [comment]
I implemented the feature, but the climate entity in Homeassistant only supports a partially featured hygrostat (a dryer).
So, you will be able to switch to the dry mode and set target humidity and tolerances.

It will be included in the next beta/release.
