### ISSUE TITLE
Feature Request: Add support for entity registry

### ISSUE THREAD

**Issue by Xelinor** [swingerman/ha-dual-smart-thermostat#2]
Currently there is no way to add the thermostat to an area. This is due to it lacking a unique_id.

Currently, it causes this error if you try and add one:
Invalid config for [climate.dual_smart_thermostat]: [unique_id] is an invalid option for [climate.dual_smart_thermostat].

Which is expected, since it's not a supported field.

Relevant documentation: https://developers.home-assistant.io/docs/entity_registry_index/

**Comment by swingerman** [comment]
Thanks for finding this. I will look into it soon.

**Comment by swingerman** [comment]
Please install v0.6.0 and let me know if the issue still exists

**Comment by swingerman** [comment]
@Xelinor, you can set a unique_id in your configuration.yaml manually

**Comment by Xelinor** [comment]
> @Xelinor Please install v0.6.0 and let me know if the issue still exists

All good! Thanks!
