### ISSUE TITLE
Heater entity turned on in `cool` hvac mode instead of cooler entity

### ISSUE THREAD

**Issue by kylegerber94** [swingerman/ha-dual-smart-thermostat#20]
For some reason, the heater entity is turned on when the thermostat is in `cool` mode.  When in `heat_cool` mode, it correctly activates the cooler and heater entities.  Also, the 'Cooling' and 'Heating' labels appear to be missing.  'Off' and 'Idle' are the only ones that show.

![image](https://user-images.githubusercontent.com/8059073/170304707-4fc01ba8-88f6-430a-9455-e16f89728590.png)
![image](https://user-images.githubusercontent.com/8059073/170304805-ea444387-00e1-4aab-81bd-f29eca6bb65d.png)

climate.yaml:
```- platform: dual_smart_thermostat
  name: Thermostat
  heater: input_boolean.fake_heat
  cooler: input_boolean.fake_ac
  target_sensor: input_number.fake_temp
  min_temp: 50
  max_temp: 80
  ac_mode: false
  # hot_tolerance: 0
  # cold_tolerance: 1
  target_temp: 70
  target_temp_low: 70
  target_temp_high: 75
  # min_cycle_duration:
  #   minutes: 5
  # initial_hvac_mode: "off"
  keep_alive:
    minutes: 1
  away_temp: 58
```

**Comment by kylegerber94** [comment]
Looking into this further, it appears the heater entity issue has been resolved here: [https://github.com/swingerman/ha-dual-smart-thermostat/commit/af30c8ed5e059164021f4ed5cff95309d21bf1ca](url)

Not sure if the missing Heating/Cooling label has been solved or not.

**Comment by swingerman** [comment]
@kylegerber94 thanks for finding this. Please check the latest release.

**Comment by kylegerber94** [comment]
@swingerman Thanks so much! I'm really impressed with your response time, and I'm looking forward to using this!
