### ISSUE TITLE
Update Bug

### ISSUE THREAD

**Issue by milandzuris** [swingerman/ha-dual-smart-thermostat#201]
Hi idk why but HA always show me (new update)

![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/42905545/c4f440ae-bb0a-4a14-9a14-ad293249052c)

**Comment by swingerman** [comment]
Not sure about this. 
Beta releases are categorized as `pre-release`. And non-beta releases are `releases`.
So, theoretically, this is right as the latest `release` is v0.9.6.
