### ISSUE TITLE
Expose some settings via entity id's. 

### ISSUE THREAD

**Issue by tomtom13** [swingerman/ha-dual-smart-thermostat#202]
Hi, it would be nice if you could expose some of the settings, like:
- high temp
- low temp
- mode

etc, with their own entity ID's. I know that this is an item that is configurable via yaml file, but even a standard thermostat exposes few settings so people can use those.

**Comment by swingerman** [comment]
All temps and models are currently exposed.

Could you please clarify what exactly you are missing?

**Comment by swingerman** [comment]
This is true. This component does not create other entities. But you can read stuff from it's state.
Go to developer tools -> states and see.

**Comment by tomtom13** [comment]
And this is useful in what way ? If I have an entity I can use it for scripting etc.

**Comment by swingerman** [comment]
You can build automation?

Can you explain what you are missing here?

**Comment by tomtom13** [comment]
Again, I might be stupid (definitely am) - if there is no entity ID, how can I change programatically a set-point / how can I access certain values from the UI directly, baring in mind that most UI requires entity_ID to get live updates from the item.

**Comment by swingerman** [comment]
In your screenshot the 'entity_id' is 'climate.office_thermostat'

What entity ids are you missing?

**Comment by tomtom13** [comment]
climate.office_thermostat_current_temp
climate.office_thermostat_max_temp
climate.office_thermostat_min_temp
climate.office_thermostat_state
climate.office_thermostat_state_reson
climate.office_thermostat_heat_on
climate.office_thermostat_fan_on
climate.office_thermostat_cool_on
climate.office_thermostat_whaever_you_think_might_be_worth_exposing

Don't you think that people might find it usefull in their UI / scripts / automations ? Also, not all items that this thermostat controls are simple switches, so right now I've got a intermediary variable that his switches, that I need to monitor to change the trv state ... a bit messy. Exposing those states via entities would help people.

**Comment by tomtom13** [comment]
Here is an example of office thermostatic valve:
<img width="1250" alt="Screenshot 2024-05-24 at 12 07 14" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/22304458/0111a87b-f840-4e3a-a182-eeab939ebcc8">
<img width="1252" alt="Screenshot 2024-05-24 at 12 07 23" src="https://github.com/swingerman/ha-dual-smart-thermostat/assets/22304458/a1a05063-e6ee-4390-b39f-46457fb3ac9e">

**Comment by swingerman** [comment]
That's MQTT integration. This component uses climate integration under the hood.
It exposes state attributes as all sensors and switches you might use to configure already have an entity in HomeAssistant. 
Thus, this component should not expose them as they are already exposed.

If you wish, I am happy to help you set up automation using state attributes. 
Whit that, I will be able to close this issue for now.

**Comment by tomtom13** [comment]
OK, so ... no entity ID's for your thermostat, just attributes for foreseeable future.
Roger.
