### ISSUE TITLE
Always turn on Cool, regardless of last mode and doesn't revert to mode if HASS is restarted, not turn off when HASS shuts down

### ISSUE THREAD

**Issue by kabongsteve** [swingerman/ha-dual-smart-thermostat#217]
1) I've noticed that when using turn_on it always starts in Cooling Mode.  

When its dual mode I would hope it turns back on the same mode it was last running in.
It would be great if it turned on to match the last mode it was operating in.

2) When HASS is restarted (software update etc) it always restarts in Off mode.

It would be great when re-started that it resumed the mode it was operating in when HASS shutdown.

3) It doesn't seem to react HASS Shutdown events
Since it always turns off when shutdown and doesn't "resume" mode when HASS restarts, then it potentially should turn off the associated header/cooler on shutdown, so that state remains consistent across the devices.

For Context:
I use it to control my Reverse Cycle AC, which has problem with maintaining consistent temp.
I now use 3 temp sensors in my house (averaging) and feed those to ha-dual-smart-thermostat

I use dummy switches for heat or cool on/off, and these set the mode of the AC unit

I use automations ha-dual-smart on the switching between heat/idle/cool/idle to adjust the temp setting of the AC
(AC setpoint is set to +/- 5 from the dual set point, thus making sure it heats, idles or cools) 

Thus when HASS shuts down, the AC is left running, but ha-dual-smart-thermostat is turned off, so no longer managing the house temperature.

Adding an automation to re-turn on dual smart only sort of works, as it always restarts Cool, and its current;ly winter here in Oz

**Comment by serlinGi** [comment]
same doubt for me;
 In this period, since I'm not having time to properly fix the dual mode, I set my thermostat:
```
heat_cool_mode: false 
keep_alive: 
  minutes: 2
initial_hvac_mode: "cool" 
ac_mode: true
```
 it works correctly but if I turn off the climate and restart the HA, the thermostat resets ON to Cool mode.

**Comment by swingerman** [comment]
@kabongsteve . Could you please post your current failing configuration? Tx.

**Comment by kabongsteve** [comment]
climate:
  - platform: dual_smart_thermostat
    unique_id: aircon
    name: AirCon
    heater: input_boolean.dummy_heat
    cooler: input_boolean.dummy_cool
    target_sensor: sensor.kitchen_temp
    min_temp: 18
    max_temp: 25
    ac_mode: true
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 120
    initial_hvac_mode: "off"
    precision: 0.1
    target_temp_step: 0.1

**Comment by swingerman** [comment]
If you set the `initial_hvac_mode`, the thermostat will activate that mode after startup or restart.
You can just remove that from your config as the thermostat should remember the last used HVAC mode.

**Comment by kabongsteve** [comment]
I did as suggested and removed "initil_hvac_mode"

Unfortunately, it still restarts in "cold" mode

**Comment by swingerman** [comment]
I tried to reproduce the issue but it works on my end just fine if I remove the `initil_hvac_mode` setting.

Could you try to create a new config with a new unique_id and see if that works?
