### ISSUE TITLE
min_cycle_duration results in gaps in cooling when using fan_hot_tolerance

### ISSUE THREAD

**Issue by Jeepmb** [swingerman/ha-dual-smart-thermostat#218]
I'm encountering some undesirable behavior when using both min_cycle_duration and fan_hot_tolerance at the same time. The issue is that when transitioning between "Cooling" and "Fan" modes (automatically via fan_hot_tolerance), the min_cycle_duration inserts an idle period of that same duration inbetween the two cooling stages, which allows the room to heat up during the idle period when it should be cooling.

The end goal (in my case) of using the min_cycle_duration is to help prevent short-cycling the Air Conditioner. My config is listed here below:

- platform: dual_smart_thermostat
  name: Office HVAC
  unique_id: hvac301
  heater: switch.147334558230384_power
  ac_mode: true
  target_sensor: sensor.t6_temperature
  fan: switch.sengled_e1c_nb7_switch
  fan_hot_tolerance: 3.0
  min_temp: 60
  max_temp: 95
  target_temp: 76
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  min_cycle_duration:
    minutes: 5
  initial_hvac_mode: "cool"
  precision: 0.1
  target_temp_step: 1.0

I belive the correct behavior should be for there to be no idle gap between transitioning from "Cooling" to "Fan" with min_cycle_duration enabled.

**My System:**
Dual Smart Thermostat v0.9.7.beta-3
Core 2024.5.1
Supervisor 2024.06.0
Operating System 12.0
Frontend 20240501.0

**Comment by swingerman** [comment]
Please check https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.7.beta-4

**Comment by Jeepmb** [comment]
Using v0.9.8.beta-5, noticed some undesirable behavior that may be related to this fix.

The program does not seem to respect the min_cycle_duration when switching between "cool" and "fan" states of the fan_hot_tolerance function. While the original issue of gaps between these two states is fixed, now it will cycle back-and-forth between "cool" and "fan" as soon as any temperature change is detected, resulting in the short-cycling that min-cycle-duration is meant to avoid.

This may have been an issue since the v0.9.7.beta-4 release, but I cannot confirm.
