### ISSUE TITLE
Offset adjustment of thermostat

### ISSUE THREAD

**Issue by admiralroflknife** [swingerman/ha-dual-smart-thermostat#231]
Is it possible to add a feature to help better utilize an external thermometer with a ac.

My current isssue is my window ac’s I use with the thermostat have an internal temp sensor that is usually off from what the room temp is. I use the dual thermostat to basically just tell the ac to turn on and off and keep it set to the lowest temp always. This is pretty inefficient as both my acs have inverters and can maintain a temp more efficiently if they’re set to a temp. Is there a way to add an offset parameter so that when I adjust the temp in the dual thermostat it adjusts the ac temp down in relation?

**Comment by swingerman** [comment]
How do you control your AC? With IR?

**Comment by swingerman** [comment]
I suggest you to create a virtual switch or script that adjust this for you
