### ISSUE TITLE
Presets not working when 'temperature' not set.

### ISSUE THREAD

**Issue by arogers86** [swingerman/ha-dual-smart-thermostat#236]
Presets do not work if the 'temperature' is not set

Readme states the following
'If temperature is not set but target_temp_low and target_temp_high are set, the temperature will be picked based on hvac mode.'

following is my YAML

    name: HVAC
    heater: input_boolean.heater_running
    cooler: input_boolean.air_con_running
    target_sensor: sensor.whole_house_average_temperature
    cold_tolerance: 0.5
    hot_tolerance: 0.3
    heat_cool_mode: false
    #initial_hvac_mode: "off" # NOTE! If this is set, the saved state will not be restored after HA restarts.
    min_temp: 10
    max_temp: 35
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 3
    precision: 0.5
    target_temp_step: 0.5
    home:
      target_temp_low: 20
      target_temp_high: 26
    away:
      target_temp_low: 12
      target_temp_high: 31
    sleep:
      target_temp_low: 15
      target_temp_high: 28

Error message when calling service 'climate.set_preset_mode'
`Failed to call service climate.set_preset_mode. Unknown error`

If I change the preset to the following, the preset works, but it does not have the desired effect when selecting heat or cool mode independantly.

    home:
      temperature: 22
      target_temp_low: 20
      target_temp_high: 26

**Comment by swingerman** [comment]
I could not reproduce this error with the latest beta

**Comment by arogers86** [comment]
Installed latest beta - confirmed working.
