### ISSUE TITLE
[bug] Other than switch entities for heater and cooler

### ISSUE THREAD

**Issue by Matz88** [swingerman/ha-dual-smart-thermostat#240]
I get no errors but if i set a entity of kind valve for heater or cooler, it is no switched correctly.
Do you confirm this behaviour from code point of view?
Would it be possible to have the possibility to have valve entities there?

**Comment by swingerman** [comment]
I need to check

**Comment by swingerman** [comment]
Could you describe the exact problem you are having? Are the valves not closing or opening, or is their current stat misrepresented?

**Comment by Matz88** [comment]
Just if a use an entity of kind valve, it is not switched at all, if a wrap it into a switch entity, then it works properly

**Comment by swingerman** [comment]
Thanks for the clarification.

**Comment by swingerman** [comment]
Please check [v0.9.8.beta-2](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.8.beta-2)
