### ISSUE TITLE
Feature request: dehumidifier mode

### ISSUE THREAD

**Issue by ejohb** [swingerman/ha-dual-smart-thermostat#25]
I use thermostat controls to control humidity instead of temperature, e.g. where the `sensor` entity is a humidity sensor, and the `switch` entities are a humidifier and a dehumidifier.

![image](https://user-images.githubusercontent.com/30390944/173592101-e15e0744-94af-41cd-99bf-8174ea4d46e1.png)

This all works perfectly with the existing logic. However it would be really nice if there could be an `humidifier_mode: true` setting that would have the following purely cosmetic changes:

- Display the unit of measure as "%", (i.e. Percent Humidity)
- Show "Humidifying"/"Dehumidifying" instead of "Heating"/"Cooling"
- Show a relevant icon (e.g. `mdi:water-percent`) instead of the snowflake/flame.

**Comment by skorpionwap** [comment]
I would like it too.  I use dual-thermostat for an AC.  It would be ideal to have a dry mode.

**Comment by swingerman** [comment]
I can look into it how to turn the climate entity to a dehumidifier

**Comment by swingerman** [comment]
The built-in dehumidifier component should work for you out of the box.

**Comment by ejohb** [comment]
> The built-in dehumidifier component should work for you out of the box.

Just to clarify, are you referring to this? https://www.home-assistant.io/integrations/generic_hygrostat/

**Comment by swingerman** [comment]
@ejohb , yes. The main problem is that thermostat cards don't support humidifier modes as far as I know.
