### ISSUE TITLE
Unable to set temperature using lovelace or scheduler component

### ISSUE THREAD

**Issue by alvaroum** [swingerman/ha-dual-smart-thermostat#26]
I have been using the Dual Smart Thermostat since a few months ago and I really love it. Recently I noticed something changed but I haven't been able to figure out what the problem is.

I have been using the custom scheduler component to set different temperatures at different times. It was working fine, but now I am not able to set temperature, only to choose the mode. I am not sure if it is a problem of the Dual Smart Thermostat component or the scheduler component to be honest, or even if it was a change on Home Assistant which made start showing this behaviour.

However, I also have found that if I don't set target_temp_low or target_temp_high in the config, I cannot make any changes on the temperatures later on using lovelace.

I tried installing previous versions of this component and the scheduler component as well, but the issue still remained, so I'm guessing that there may be a change within Home Assistant that now changed the behaviour of one of these components.

**Comment by swingerman** [comment]
Ther have been a few release. If you still using the component, could you check if it's still an issue for you?
