### ISSUE TITLE
[bug] - toggling fan_hot_tolerance malfunction

### ISSUE THREAD

**Issue by swingerman** [swingerman/ha-dual-smart-thermostat#264]
It seems if you toggle the fan_hot_tolerance_toggle entity, it will immediately turn on the cooling device (whether AC or fan depending on toggle state) regardless of the temperture or set point.

_Originally posted by @Jeepmb in https://github.com/swingerman/ha-dual-smart-thermostat/issues/255#issuecomment-2273415226_

**Comment by swingerman** [comment]
PLease check [v0.9.8.beta-5](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.8.beta-5)

**Comment by Jeepmb** [comment]
Testing beta-5 now, appears to be resolved so far.
