### ISSUE TITLE
[bug] - min_cycle_duration not respected

### ISSUE THREAD

**Issue by swingerman** [swingerman/ha-dual-smart-thermostat#270]
Using v0.9.8.beta-5, noticed some undesirable behavior that may be related to this fix.

The program does not seem to respect the min_cycle_duration when switching between "cool" and "fan" states of the fan_hot_tolerance function. While the original issue of gaps between these two states is fixed, now it will cycle back-and-forth between "cool" and "fan" as soon as any temperature change is detected, resulting in the short-cycling that min-cycle-duration is meant to avoid.

This may have been an issue since the v0.9.7.beta-4 release, but I cannot confirm.

_Originally posted by @Jeepmb in https://github.com/swingerman/ha-dual-smart-thermostat/issues/218#issuecomment-2289936809_

**Comment by mat1990dj** [comment]
Duplicated of #12 ?

**Comment by swingerman** [comment]
Could you please post your current configuration?

**Comment by swingerman** [comment]
So when the thermostat wants to change from cooling to fan, but the cooler still needs to be cycled out. What do you think we should do?
- don't touch the cooler, and turn the fan on or
- don't change anything until the cooler cycles out?

**Comment by Jeepmb** [comment]
I think the appropriate action would be the second option. Don't change anything until the cooler cycles out.

Also, I changed my configuration a while back to work around this issue, and can't remember the exact config, so I don't want to post anything that may be inaccurate. But I can try and re-create it for testing if required.

**Comment by swingerman** [comment]
The fix is ready. I will include it in the next release.

**Comment by mat1990dj** [comment]
0.9.9 still reproduces the same behavior, of by accident someone can get the temperature to a higher setpoint and the heater turns on, and you inmediately change the temperature setpoint back, the min_cycle is not respected and the off signal is sent right away

**Comment by swingerman** [comment]
This is intended behaviour. The built-in thermostat in HA works the same way. Setting target temperatures is considered intentional, and thus, they override every current behaviour.

**Comment by mat1990dj** [comment]
ok, I thought this would override it. What one wants with the min cycle duration is to respect the heating/cooling device cycle, my AC needs to run a minimum of 1 minute too, to have the oil lubricate the system.
Shouldnt this behavior be changed?

**Comment by Jeepmb** [comment]
For what it's worth, I am in favor of the current behavior of responding instantly to manual temperature set point changes. 

While I expect the normal operational cycling to respect the min cycle duration to reduce wear like @mat1990dj describes, I think it's important for the system to respond to my inputs instantaneously when needed. I believe the intent of those minimum run time requirements for HVAC devices is to prevent damage from very frequent short-cycling, not occational set point changes.
