### ISSUE TITLE
[bug] - hvac_power_level when off

### ISSUE THREAD

**Issue by Bergoglio** [swingerman/ha-dual-smart-thermostat#276]
Hi,

three bugs that I found :

1. I don't know if it happens only in my Home Assistant but in Settings > Device & Services > Integrations > Dual Smart Thermostat it continues to show me 0.9.6 even if I installed 0.9.8.beta.6 version 
![Screenshot_20240829_091826](https://github.com/user-attachments/assets/c6e61a38-8081-41ec-9c15-b2f7a94bcdf3)

2. even if hvac_action_reason: opening and / or hvac_action: off (so, when the thermostat switch off heater and cooler for different reasons than achieved target temperature) hvac_power_level and hvac_power_percent stay with values different from 0
![Screenshot_20240829_093432](https://github.com/user-attachments/assets/2894f22b-d561-49d1-bab1-681d5863990f)

3. it continues to show hvac_power_percent value with a lot of decimals instead of an int number and hvac_power_level show 2.0 instead of 2 (0, 1 and 3 are ok; i cannot test more because my fancoils are a 3-speeds type)

**Comment by swingerman** [comment]
Please check [v0.9.8.beta-7](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.8.beta-7)

**Comment by Bergoglio** [comment]
The problems were the same in 0.9.8.beta-7

**Comment by Bergoglio** [comment]
But speed 2 is fixed
![Screenshot_20240829_125750](https://github.com/user-attachments/assets/b7e8fd5c-1c0d-42da-a1bb-512510303204)

**Comment by Bergoglio** [comment]
Also in speed 2 hvac_power_percent doesn't show 66,66666666 but 67
The problem of 33,333333333 is only on speed 1

**Comment by swingerman** [comment]
Please check [v0.9.8.beta-8](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.8.beta-8)

**Comment by Bergoglio** [comment]
Ok, power levels now work good on device state changes.

Remain only speed 1 - percentage 33,333333333 as You can see
![Screenshot_20240830_125350](https://github.com/user-attachments/assets/a453def1-78d1-4448-a71d-255e53a825e4)

**Comment by swingerman** [comment]
OK. It's foxed now in [v0.9.8.beta-9](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.8.beta-9)

**Comment by Bergoglio** [comment]
Ok, it is fixed !
Good work, well done !
