### ISSUE TITLE
Feature request: Dynamic setting min. and max. 

### ISSUE THREAD

**Issue by janrunhartIT** [swingerman/ha-dual-smart-thermostat#28]
Is it possible to change the min. and max. temperature to a dynamic value (template / state / variable)?

**Comment by seganku** [comment]
Having the flexibility to set temps to a Helper (`input_number`) would give people a lot more options for automation:
- min_temp
- max_temp
- max_floor_temp
- target_temp
- target_temp_low
- target_temp_high

**Comment by swingerman** [comment]
The underlying climate platform works with service calls. The values used in the YAML are only used to set up the component. So even if we were setting a dynamic value there, it will be used only once.
You should use the 
climate.set_temperature service
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/7681395/192827996-96d20e60-a2a0-45b8-a762-63a2703b3b6d.png">

reference: https://www.home-assistant.io/integrations/climate/
