### ISSUE TITLE
[chore] warning doesn't say which sensor is stalled

### ISSUE THREAD

**Issue by swingerman** [swingerman/ha-dual-smart-thermostat#286]
I had a Quick Look through the commit and I couldn't see if the logging will include information about which entity is causing the issue in the log, i.e:

```
01.194 WARNING (MainThread) [custom_components.dual_smart_thermostat.climate] Sensor is stalled, call the emergency stop
```

This doesn't say which sensor is stalled, and which entity the emergency stop has been called on.

I realise hvac_action_reason is set, but often this is empty by the time I want to look at it, which is why it would be good to log it so I can correlate it with an issue.

_Originally posted by @jacobw in https://github.com/swingerman/ha-dual-smart-thermostat/issues/268#issuecomment-2328488207_

**Comment by swingerman** [comment]
This one will make it more informative

**Comment by jacobw** [comment]
Thank you @swingerman !
