### ISSUE TITLE
[bug] Component doesn't report current status/"hvac_action" in Heat Pump (one switch heat/cool) mode

### ISSUE THREAD

**Issue by Andrecall** [swingerman/ha-dual-smart-thermostat#292]
Hi, 
First of all, thank you for this awesome thermostat component, that is finally something HA-based, which should and actually works with Heat Pump, that has only one switch for heat/cool.

As I said everything works as expected except **"hvac_action" status. It just missing**( see screenshot). As a result the thermostat entity doesn't show if it's idle or actively cooling/heating. 
I did some tests and if I remove "heat_pump_cooling: sensor.study_heat_pump_state" from config and switch to simple heat or cool mode, it starts reporting the "hvac_action" status.

![267032b4-c8c3-4533-aa7d-0ec7d89d1da7](https://github.com/user-attachments/assets/79585961-9722-4cf1-9a23-70069d3e110d)

**Comment by swingerman** [comment]
Please check [v0.9.8.2](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.8.2)

**Comment by Andrecall** [comment]
> Please check [v0.9.8.2](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.8.2)

Now everything works completely fine! Status is reported and displayed in a thermostat entity.

Thank you for a very quick fix!
