### ISSUE TITLE
Feature request: target_sensor not only sensor entity

### ISSUE THREAD

**Issue by dala318** [swingerman/ha-dual-smart-thermostat#30]
I'm planning to use this as an extension to a less capable physical thermostat (heat only)
But as the dual_smart_thermostat need the target_sensor to be a thermometer with state as temp I have to go the way around to create a template sensor to extract the actual temperature from my climate entity.
Would like to either allow climate entities as target_sensor, or that you can specify any input formula you want.
E.g. `  target_sensor: "{{ state_attr('climate.thermostat_hallway', 'current_temperature') }}"`

**Comment by dala318** [comment]
When thinking of it a bit more, maybe the climate entity should be a different configuration setting, in that case the state of the entity [off, heat_cool, ...] could also affect the state of the dual-smart-thermostat.

**Comment by swingerman** [comment]
I don't plan to support the target_sensor other than sensors.
