### ISSUE TITLE
2 stage heating and 1 stage cooling with Fan

### ISSUE THREAD

**Issue by bhupiister** [swingerman/ha-dual-smart-thermostat#321]
Hi. Appreciate all the efforts. 
Is there an example for 2 stage heating with 1 stage cooling + Fan ? 
It should auto switch between two stages of heating. And should auto switch between heating and cooling mode. 
I am not sure of the Fan logic. But my existing thermostat controls the fan with option of auto, off, on. 

Is your **Full configuration example** already covering this?

**Comment by bhupiister** [comment]
![image](https://github.com/user-attachments/assets/7801fc05-8ed7-4bf7-861f-2f911e9f68fd)

I was reading manual for my thermostat and as per the picture attached, i can program my furnace to single stage and let it control the logic for the firing sequence. 

Should i go for this option rather along with your preset for cool+heat+fan?

**Comment by bhupiister** [comment]
Just realized one more important thing about FAN.
There are two modes, AUTO and ON. 

**AUTO** means there will be no "G" output. The furnace controller will automaticlly turn the FAN on with call for heat or cooling.
**ON** means, there will be "G" output. This will make furnace keep the FAN in always on mode.

So there is no complex programming related to FAN, Just an ON of OFF switch.

So, to sum up, all I need is a heat and cool mode with a Fan Auto/On mode. I'm setting my thermostat to handle a two-stage furnace logic, so I do not have to worry about it.

I also need to make sure that the cooling and heating commands do not activate at the same time. This can happen if I use a relay, and contacts get welded, or if there is an error in the coding. But this can easily be handled in the relay wiring logic.

**Comment by swingerman** [comment]
We already support [cooling+fan](https://github.com/swingerman/ha-dual-smart-thermostat?tab=readme-ov-file#fan-with-cooler-mode). And we also support [two-stage heating](https://github.com/swingerman/ha-dual-smart-thermostat?tab=readme-ov-file#two-stage-aux-heating)
