### ISSUE TITLE
Fan not turning on with heat.

### ISSUE THREAD

**Issue by gcs8** [swingerman/ha-dual-smart-thermostat#326]
Hey, when I set heat to get it to turn on, it's not also triggering the fan switch like it does with AC. can't figure it out with the current docs, I need an adult.
```  
- platform: dual_smart_thermostat
    name: "House HVAC"
    unique_id: house_hvac
    target_sensor: sensor.house_temp_mid_1st_floor_temperature
    heater: switch.esp_thermostat_heat
    cooler: switch.esp_thermostat_ac
    fan: switch.esp_thermostat_fan
    fan_on_with_ac: true
    fan_hot_tolerance: 1
    heat_cool_mode: true
    ac_mode: true
    cold_tolerance: 1
    hot_tolerance: 1
    initial_hvac_mode: "heat_cool"
    min_temp: 65
    max_temp: 85
    keep_alive:
      minutes: 3

**Comment by swingerman** [comment]
The component doesn't support heating, which triggers the fan too.
There is already a request for this #252

**Comment by crazybananas25** [comment]
simple solution? why not group your switches for heat with your fan switch so when it calls for heat it always turns on the fan switch
