### ISSUE TITLE
Feature Request: 2 stage heating

### ISSUE THREAD

**Issue by ecard0** [swingerman/ha-dual-smart-thermostat#4]
Hi, I have been looking for this for a while :)   Would it be possible to add a second heater switch for a second stage with a different tolerance?

Thanks,
Eric

**Comment by swingerman** [comment]
Hi, could you please describe the scenario in detail? When the second heater switch should turn on?

**Comment by rvdbijl** [comment]
I second this request! In my view the 2-stage should turn on when:
1. The outdoor temperature is below or above a certain value (when heating or cooling).
2. The heating/cooling has been on for at least x amount of time and the setpoint has not yet been satisfied. 
3. In the case of (2), it should remember that it had to use the 2nd stage to get to the desired temperature in a reasonable amount of time, and turn it on immediately on the next cycle. Perhaps reset (unlatch) overnight.

**Comment by swingerman** [comment]
I see. It seems like a nice feature. I will consider implement it after all other open bugs are fixed (soon)

**Comment by sahirmathur1** [comment]
Second this! I have 2 heaters exposed to Home Assistant in the same room, would like to set 1 temperature and let the thermostat manage which heater to turn on.

**Comment by swingerman** [comment]
So, let's confirm: if stage2 heater is on, stage1 heater should be off, right?

**Comment by swingerman** [comment]
@ecard0 , @rvdbijl is implemented in: [v0.9.4-beta.0](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.4-beta.0)

Please install and check!

 - readme update on how to configure
 - the secondary heater will turn on after a timeout
 - it will be remembered for that day and will turn on the secondary heater that day
 - primary heater is turned off while the secondary heater is on

**Comment by ecard0** [comment]
@swingerman 

Thanks a lot :)

You should also implement a different cold tolerance for stage 2.  Currently, my stage 1 kicks in if the cold tolerance is 0.1.  And the stage is cold tolerance is set to 0.3.   So normal use the stage 1 is running, but in the morning, when the furnace kicks in and needs to bring temp from 18 to 21, stage 2 turns on immediately.

Eric
