### ISSUE TITLE
What about "min_floor_temp:"

### ISSUE THREAD

**Issue by luckysession** [swingerman/ha-dual-smart-thermostat#41]
Hi @ll,

what about "min_floor_temp:" ?

Thank you!
lucky

**Comment by swingerman** [comment]
Could you describe the expected logic?
What if we reached the raget temp but not the min_floor_temp, for example?

**Comment by luckysession** [comment]
Hi,

would be interest for savety in case of frost - maby - must work without thermostat "on"

Thank you

**Comment by swingerman** [comment]
Setting a thermostat's away temp to a nonfrost temp will accomplish this.

**Comment by dankarization** [comment]
Hi. I'm jumping into this old issue with another implementation of min_floor_temp. If it's a warm winter day and your ambient temperature is warm enough, heating can stay turned off for a long time, so your floor becomes cold to the touch (but with no problems seen to thermostat logic).
It would be great to be able to still turn on heating just to warm up the floor a bit, even if it will overshoot room temperature.
I guess there's at least 3 values needed for this logic to work properly: `min_floor_temp`, `timeout` and `max_room_temp`
If floor temperature is lower than `min_floor_temp` for `timeout` or longer, then we turn on heating ignoring the fact that it's already warm enough, but if room temperature is greater than `max_room_temp`, then we turn it off

**Comment by swingerman** [comment]
One way I think it could or should work is to switch the thermostat to a "floor temperature thermostat". Where the current temperature is not the room temperature but the floor temperature, my concern is that the UI should give you an idea of what's going on. It will be very confusing to be honest.

**Comment by dankarization** [comment]
I don't like the idea of a thermostat controlling only the floor temperature not being aware of the actual room temp 🥺

**Comment by swingerman** [comment]
Well, the simplest way to do it would be just to set the min_floor_floor_temp, and the thermostat won't turn off until it's reached. I could inject this extra logic when I check if the room is warm enough by adding (and the floor is warm enough, too)
I also planned to introduce some attributes of the thermostat that communicate the reason for current state

**Comment by swingerman** [comment]
@alvarocarrera @dankarization. I added the logic, please try the [v0.9.3-bata](https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.3-beta.0)

**Comment by swingerman** [comment]
@luckysession @dankarization . Did you have a chance to try the above beta for minimum floor temperature?

**Comment by dankarization** [comment]
Not yet, my sensor board needs some work to be done first(
