### ISSUE TITLE
Why is target temp step limited to less than or equal to 1?

### ISSUE THREAD

**Issue by Hellis81** [swingerman/ha-dual-smart-thermostat#50]
Can't it be set to what you want?
I understand the normal usage of this integration is house/apartment heating but I'm using it for a BBQ and setting the temperature in 5 or 10 degrees makes more sense.
Is there any reason why this is hardcoded this way?

EDIT; I mean I use the thermostat to track the temperature inside the BBQ not in the meat

**Comment by swingerman** [comment]
You can use the target_temp_step to control this
