### ISSUE TITLE
Card control dot disappears after recent Home Assistant update

### ISSUE THREAD

**Issue by valuta1995** [swingerman/ha-dual-smart-thermostat#52]
After updating to Home Assistant 2023.3.0 the control 'orb' on the slider has disappeared and the card can no longer be controlled. I can still adjust it otherwise.
![image](https://user-images.githubusercontent.com/14346905/222299072-bb555447-e9b7-4345-8b47-b74455a8d05b.png)

**Comment by swingerman** [comment]
This issue seems to be related to the Home Assitant UI update in 2023.3.0, not this component. I saw others reporting the same issue for other components as well.

**Comment by swingerman** [comment]
I think so
