### ISSUE TITLE
Feature Request - open time for openings

### ISSUE THREAD

**Issue by Anon666333** [swingerman/ha-dual-smart-thermostat#56]
It would be great if we could specify how long an opening is open before adjusting the thermostat.

For example, I have my back door as an opening and the ac will turn off when it's opened, but sometimes you're just opening it to go outside, not to leave it open. So instead of the ac turning on and off on and off it would be nice to set a time limit for how long the door needs to be open before any changes happen to the thermostat.

**Comment by swingerman** [comment]
The feature can be tested in https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.0-beta.2
