### ISSUE TITLE
Switch gets randomly turned on and off

### ISSUE THREAD

**Issue by oxymoron1629** [swingerman/ha-dual-smart-thermostat#6]
I'm trying to wrap my head around the behavior this component seems to take. Before is my config.
`   platform: dual_smart_thermostat

    name: Virtual Bedroom
    heater: switch.bedroom_ac_heat
    cooler: switch.bedroom_ac_cool
    target_sensor: sensor.bedroom_temperature_sensor_temperature
    min_temp: 55
    max_temp: 80
    ac_mode: false
    target_temp: 68
    target_temp_high: 73
    target_temp_low: 68
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 2
    initial_hvac_mode: "heat_cool"
    away_temp: 60
    precision: 0.1`

For some reason, despite the temperature being outside the target temp and tolerance, the component keeps turning the switch on and off repeatedly. See log of the switch.

![Screenshot_20220401-153729_Home Assistant](https://user-images.githubusercontent.com/69619724/161330367-7c5314df-5a15-45f6-a915-18e6d5fe86ef.jpg)

Any ideas why this would be happening? Is it an issue with my config? What's weird to me is that it's toggling the switch faster than the minimal cycle duration. Any help would be greatly appreciated.

**Comment by swingerman** [comment]
please install the latest version (0.6.0) and let me know if it still exists

**Comment by eSeR1805** [comment]
I'm also seeing this
![image](https://user-images.githubusercontent.com/61332999/197867781-9b375f08-7cdf-4ba7-8813-3e6d6d962abb.png)
On latest version:
![image](https://user-images.githubusercontent.com/61332999/197867869-4c9a0f27-1606-4cb5-91cd-787386638a45.png)
Config:
`climate:
  - platform: dual_smart_thermostat
    name: Thermo2
    heater: switch.sonoff_1000a7dfc0
    cooler: climate.daikinap67520
    target_sensor: sensor.bedroom_temperature
    openings:
      - binary_sensor.door_and_window_sensor_6a40
      - binary_sensor.door_and_window_sensor_cb42
      - binary_sensor.door_and_window_sensor_f364_contact_sensor_f364
    min_temp: 15
    max_temp: 30
    ac_mode: false
    target_temp: 20
    target_temp_high: 25
    target_temp_low: 20
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode vill reset to this value after restart
    away_temp: 17
    precision: 0.1`

**Comment by swingerman** [comment]
Added a fix that you can test in the latest beta: https://github.com/swingerman/ha-dual-smart-thermostat/releases/tag/v0.9.0-beta.2
