### ISSUE TITLE
Temperature not showing up on thermostat

### ISSUE THREAD

**Issue by alexfrench** [swingerman/ha-dual-smart-thermostat#62]
I have set up a number of thermostats in configuration.yaml, as follows. They all appear in my dashboard correctly. I have a number of temperature sensors, appropriately named, configured using mqtt-io running on raspberry pi devices. 

However, having seen temperatures for each of the sensors I have so far installed (lounge, studio and family) appearing in their related thermostat individually, I am only seeing one temperature at present on themostats on my dashboard. 

MQTT Explorer shows valid messages being received. Also, when I check the HA entities I can see the correct values are being received. 

Any ideas why this might be happening?

UPDATE: A few hours and a restart later only the Family Room temp is showing, although all three of the installed thermostats are generating data which can be seen by HA.

climate:
  - platform: dual_smart_thermostat
    name: Study
    heater: switch.study_heater
    cooler: switch.study_cooler
    target_sensor: sensor.study_temperature
    min_temp: 6
    max_temp: 30
    ac_mode: false
    target_temp: 17
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort: 
      temperature: 18
    precision: 0.1
    target_temp_step: 0.5
  - platform: dual_smart_thermostat
    name: Bed 1
    heater: switch.bed1_heater
    cooler: switch.bed1_cooler
    target_sensor: sensor.bed1_temperature
    min_temp: 6
    max_temp: 30
    ac_mode: false
    target_temp: 17
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort: 
      temperature: 18
    precision: 0.1
    target_temp_step: 0.5
  - platform: dual_smart_thermostat
    name: Bed 2
    heater: switch.bed2_heater
    cooler: switch.bed2_cooler
    target_sensor: sensor.bed2_temperature
    min_temp: 6
    max_temp: 30
    ac_mode: false
    target_temp: 17
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort: 
      temperature: 18
    precision: 0.1
    target_temp_step: 0.5
  - platform: dual_smart_thermostat
    name: Bed 3
    heater: switch.bed3_heater
    cooler: switch.bed3_cooler
    target_sensor: sensor.bed3_temperature
    min_temp: 10
    max_temp: 28
    ac_mode: false
    target_temp: 17
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort: 
      temperature: 18
    precision: 0.1
    target_temp_step: 0.5
  - platform: dual_smart_thermostat
    name: Bed 4
    heater: switch.bed4_heater
    cooler: switch.bed4_cooler
    target_sensor: sensor.bed4_temperature
    min_temp: 6
    max_temp: 30
    ac_mode: false
    target_temp: 17
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort: 
      temperature: 18
    precision: 0.1
    target_temp_step: 0.5
  - platform: dual_smart_thermostat
    name: Family Room
    heater: switch.family_heater
    cooler: switch.family_cooler
    target_sensor: sensor.family_temperature
    min_temp: 10
    max_temp: 28
    ac_mode: false
    target_temp: 17
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort: 
      temperature: 18
    precision: 0.1
    target_temp_step: 0.5
  - platform: dual_smart_thermostat
    name: Office
    heater: switch.office_heater
    cooler: switch.office_cooler
    target_sensor: sensor.office_temperature
    min_temp: 6
    max_temp: 30
    ac_mode: false
    target_temp: 17
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort: 
      temperature: 18
    precision: 0.1
    target_temp_step: 0.5
  - platform: dual_smart_thermostat
    name: Studio
    heater: switch.studio_heater
    cooler: switch.studio_cooler
    target_sensor: sensor.studio_temperature
    min_temp: 6
    max_temp: 30
    ac_mode: false
    target_temp: 17
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort: 
      temperature: 18
    precision: 0.1
    target_temp_step: 0.5
  - platform: dual_smart_thermostat
    name: Lounge
    heater: switch.lounge_heater
    cooler: switch.lounge_cooler
    target_sensor: sensor.lounge_temperature
    min_temp: 6
    max_temp: 30
    ac_mode: false
    target_temp: 17
    target_temp_high: 26
    target_temp_low: 23
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat_cool" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 13
      target_temp_low: 12
      target_temp_high: 14
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 21
    comfort: 
      temperature: 18
    precision: 0.1
    target_temp_step: 0.5

At the current time, I am seeing a temp from a device which is not running, while others that are running are not showing! 

![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/2207848/8cf0b549-c3bf-40b3-994d-288888f538cb)

**Comment by dugancom** [comment]
Not sure if this will help but I am experiencing this too and when I click one of the modes on the thermostat the temperature shows up.

**Comment by swingerman** [comment]
i will publish a release soon that should fix it. The capabilities and available modes set up for the component were a bit buggy
