### ISSUE TITLE
Power consumtion is not working

### ISSUE THREAD

**Issue by Borty97** [swingerman/ha-dual-smart-thermostat#74]
Carrier Wi-Fi Smart AC has `sensor.[climate_name]_total_energy_consumption` and `sensor.[climate_name]_realtime_power` but no one is retrieving the real data

![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/60492018/cf8a2075-6718-4cc7-9c12-fcb5e1b88faa)

**Comment by swingerman** [comment]
The power consumption is outside the scope of this component.
