### ISSUE TITLE
Dual termostat heat and cool with only one switch

### ISSUE THREAD

**Issue by soscomo** [swingerman/ha-dual-smart-thermostat#79]
Hello,m i have aeroterm machine, with radian floor, I have a solenoid valve and a thermometer in each room. I config a dual termostac for each room, but only can change from off to heat mode, because y only have one switch for heat and cold, is the same switch.

Is it possible to configure hot and cold mode with a single switch?

or i hve to config one termostac to cool mode and another to heat mode.

thanks

**Comment by swingerman** [comment]
I am not familiar how your machine works. Could you exolain how it works? Is it a heater?

**Comment by soscomo** [comment]
Hello, is a heat pump air/water, my system is vaillant, and can change parameters with ebusd addon in HA, but only can manage one room.  the model is Vaillant aroTHERM VWL 115/2 + UniTOWER VIH QW 190/1 E.
This system need radiant floor, and heat or cold the liquid. 

I prefer manage the rooms separately, so install a rele in each solenoid valve, this rele open or close the room circuit, so i connect in HA ble termometer for manage it, so i config the dual termostat, but i have only one switch (rele), so i only can turn off or heat.

**Comment by swingerman** [comment]
I see. In this case you must set some helper entities in Home Assistant to make it work.

1. You need an automation that changes the HVAC mode on the thermostat to the current HVAC mode of the heat pump(HEAT/COOL)
2. The thermostat can do the rest.

If you try to control the heat pump per room, you will not be able to do heating and cooling at the same time. But maybe it's not required after all.

So if you want the thermostat to control your heat pump:

- you need a switch that runs a script on the ON and OFF state for both the heater and cooler switch entities.
- the script must set the heat pump to heat or cool and set the valve state for the room on/off
- 
Obviously, the switches should work the opposite way in regards to the HVAC mode of your heat pump.

I hope this makes sense.

**Comment by soscomo** [comment]
thanks for your answer, and sorry for my english ;)

You are on the correct way, the heat pump only change mode two times a year, so this is no the problem.

I only want to change hvac mode in dual termostat i had create for each room. I think about your idea to make a script ot  create a false switch to use in cold mode, that control the original switch that i use to heat mode, that work in the opposite way.

i´ll try this idea.

**Comment by marcocalvini** [comment]
you can create a new helper using "Change device type of a switch" and set it as light, after that you can use the normal switch as cooler and the helper as heater
