### ISSUE TITLE
AC not being turned off after successfully being turned on

### ISSUE THREAD

**Issue by delitero** [swingerman/ha-dual-smart-thermostat#81]
Hello,
Im controlling my Midea AC through an USB dongle with ESPHome, when I set the thermostat to cool it was able to turn on the AC.

> Living room AC  changed to Heat/Cool triggered by service Home Assistant Core Integration: Generic turn on

Unfortunately it doesn't seems to be able to switch it off after I set the target temp lower the current temp or change the thermostat mode to off. Is this a bug or AC's are not being supported?

**Comment by swingerman** [comment]
If you still having the issue please provide your current configuration
