### ISSUE TITLE
advise min cycle duration

### ISSUE THREAD

**Issue by lizznl** [swingerman/ha-dual-smart-thermostat#86]
Hi,

The dual smart thermostat looks awesome! I have some questions regarding the min_cycle_duration, could somebody please give me advise about it?

Using an ESPHome board with mechanical valves behind it to turn on the floor heating with a heat pump behind it.

Is it common that based on the min cycle, in this situation 20 minutes on, 20 minutes off is advised? I tought the 'on'  period would maybe extend if the target temperature isn't accomplished yet. Secondly would 20 minutes be ok for floor heating with a heat pump or should it be 10 minutes on, 10 minutes off?

Thanks in advance!

Lizzie

**Comment by swingerman** [comment]
Since the thermostat will only control the valves, I think you should not need to adjust the cycle duration in the thermostat.
