### ISSUE TITLE
Depcrecated supported featured after upgrade 2024.1.1

### ISSUE THREAD

**Issue by lizznl** [swingerman/ha-dual-smart-thermostat#89]
Hi,

After upgrading to 2024.1.1 Home Assistant notifies deprecated helpers:

 (<class 'custom_components.dual_smart_thermostat.climate.DualSmartThermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|PRESET_MODE: 17>

Any ideas?

**Comment by swingerman** [comment]
Thanks for finding this. It seems that some feature values need to be updated. I will schedule this for todo. The component should work OK until 2025.1.

**Comment by serlinGi** [comment]
Hi, same warning for other values too

![Screenshot_2024-01-12-23-18-08-20_c3a231c25ed346e59462e84656a70e50](https://github.com/swingerman/ha-dual-smart-thermostat/assets/63103970/63a2b682-111c-4826-b7bc-e21ffab30868)
job
thx for your

**Comment by swingerman** [comment]
The fix will be rolled out in the next release
