### ISSUE TITLE
Two items heating

### ISSUE THREAD

**Issue by Stefan19777** [swingerman/ha-dual-smart-thermostat#9]
I have an underfloor system where I am opening a valve with your dual smart thermostat. I want also to switch at the same time the pump on. How can I add two (or more) items to the string? 
Hope you can help me, thank you.

Example of what I have. I want to add       switch.1_kinderkamer_cv3 to the heater:
climate:
  - platform: dual_smart_thermostat
    name: Zolder
    heater: 
      switch.1_kinderkamer_cv4
    target_sensor:
      sensor.lumi_lumi_weather_0f08e207_temperature
    min_temp: 15
    max_temp: 22.5
    ac_mode: false
    target_temp: 19
    target_temp_high: 26
    target_temp_low: 23
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 10
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off"
    precision: 0.1

**Comment by swingerman** [comment]
I would create an automation. I do it like that in my system (I have 4 zones)
