### ISSUE TITLE
Heating is not stopping when i start cooling mode

### ISSUE THREAD

**Issue by marcocalvini** [swingerman/ha-dual-smart-thermostat#90]
Hi,

when change mode from heater to cooler with heating running, heating switch will not switched off as you can see in below picture.

![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/122184394/7b116806-4923-4e3b-961c-3748cd65dff5)

here the configuration
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/122184394/9020a35d-e39a-411b-9e27-c68a22e0bec8)

**Comment by marcocalvini** [comment]
Climate Configuration
![image](https://github.com/swingerman/ha-dual-smart-thermostat/assets/122184394/c8eeb7d0-b5cc-4203-866b-5e5809a77fe1)

**Comment by swingerman** [comment]
Thanks for finding this. I will schedule this for todo.

**Comment by marcocalvini** [comment]
Will it be included in the next release (0.93)?
