### ISSUE TITLE
Question - 2 stage heating

### ISSUE THREAD

**Issue by nlindblo** [swingerman/ha-dual-smart-thermostat#95]
Is it possible to use 2 stage heating where the second heater kicks in without the primary turning off ? I have both radiators (without smart valves) that uses an average termerature across rooms and aircon heaters in some rooms and I would like to use the aircon heaters to kick in when the radiators haven't reach the temperature after a set period

**Comment by swingerman** [comment]
I can do that.

**Comment by swingerman** [comment]
This was implemented in the latest release
